import type { SurveyQuestionConfig } from "../types/graduate";

/**
 * Las 10 preguntas del cuestionario "Tu proyección profesional".
 *
 * Los `value` son estables: son lo que se guardará en la base de datos.
 * Cambiar un `label` no afecta nada; cambiar o eliminar un `value` sí.
 *
 * Áreas (4), sectores (5) y competencias (7) usan los mismos valores que el
 * recomendador de programas del backend (app/preguntas.py), para que al
 * conectar la API las respuestas se crucen directamente con el catálogo UNIR.
 */
export const SURVEY_QUESTIONS: SurveyQuestionConfig[] = [
  {
    id: "employmentStatus",
    type: "choice",
    shortLabel: "Situación laboral",
    text: "¿Cuál es tu situación laboral actual?",
    help: "Elige la opción que mejor describe tu situación hoy.",
    options: [
      { value: "tiempo_completo", label: "Trabajo a tiempo completo" },
      { value: "tiempo_parcial", label: "Trabajo a tiempo parcial" },
      { value: "independiente", label: "Soy independiente o emprendedor" },
      { value: "buscando_empleo", label: "Estoy buscando empleo" },
      { value: "no_busco_empleo", label: "Actualmente no busco empleo" },
    ],
  },
  {
    id: "targetRole",
    type: "text",
    shortLabel: "Cargo al que aspiras",
    text: "¿Cuál es el cargo o rol profesional al que aspiras?",
    help: "Escríbelo con tus palabras. Nos ayuda a sugerirte formación y oportunidades acordes.",
    placeholder: "Ej. Líder de analítica, director de proyectos, especialista en seguridad…",
    maxLength: 150,
  },
  {
    id: "preferredEducationType",
    type: "choice",
    shortLabel: "Formación de interés",
    text: "¿Qué tipo de formación te interesa continuar?",
    help: "Piensa en tu siguiente paso de formación, aunque no sea inmediato.",
    options: [
      { value: "curso_corto", label: "Curso corto o certificación" },
      { value: "diplomado", label: "Diplomado o programa de experto" },
      { value: "especializacion", label: "Especialización" },
      { value: "maestria", label: "Maestría" },
      { value: "doctorado", label: "Doctorado" },
      { value: "ninguna", label: "Por ahora no deseo continuar" },
    ],
  },
  {
    id: "preferredPerformanceArea",
    type: "choice",
    shortLabel: "Área de desempeño",
    text: "¿En cuál área de desempeño te visualizas?",
    help: "Elige la que más se acerque a lo que quieres hacer en los próximos años.",
    options: [
      { value: "direccion_empresas", label: "Dirección y gestión de organizaciones" },
      { value: "finanzas", label: "Finanzas y contabilidad" },
      { value: "comercial_marketing", label: "Comercial, ventas y marketing" },
      { value: "talento_humano", label: "Talento humano" },
      { value: "educacion", label: "Educación y pedagogía" },
      { value: "tecnologia", label: "Tecnología y transformación digital" },
      { value: "datos_ia", label: "Datos, analítica e inteligencia artificial" },
      { value: "ciberseguridad", label: "Ciberseguridad" },
      { value: "proyectos", label: "Gestión de proyectos" },
      { value: "logistica", label: "Logística y operaciones" },
      { value: "juridica_publica", label: "Derecho y gestión pública" },
      { value: "salud_sst", label: "Salud y seguridad en el trabajo" },
      { value: "comunicacion", label: "Comunicación y contenidos" },
      { value: "sostenibilidad", label: "Medio ambiente y sostenibilidad" },
      { value: "otra", label: "Otra área" },
    ],
  },
  {
    id: "preferredEconomicSector",
    type: "choice",
    shortLabel: "Sector económico",
    text: "¿En cuál sector económico te gustaría trabajar?",
    help: "Si dudas entre varios, elige el que más te atrae.",
    options: [
      { value: "tecnologia", label: "Tecnología y telecomunicaciones" },
      { value: "educacion", label: "Educación" },
      { value: "financiero", label: "Banca, seguros y servicios financieros" },
      { value: "salud", label: "Salud" },
      { value: "publico", label: "Gobierno y sector público" },
      { value: "industria", label: "Industria y manufactura" },
      { value: "logistica_transporte", label: "Transporte y logística" },
      { value: "comercio", label: "Comercio y retail" },
      { value: "consultoria", label: "Consultoría y servicios profesionales" },
      { value: "construccion_energia", label: "Construcción, energía y minería" },
      { value: "agro", label: "Agroindustria" },
      { value: "social", label: "ONG y organizaciones sociales" },
      { value: "turismo_cultura", label: "Turismo, cultura y entretenimiento" },
      { value: "otro", label: "Otro sector" },
    ],
  },
  {
    id: "yearsOfExperience",
    type: "choice",
    shortLabel: "Experiencia",
    text: "¿Cuántos años de experiencia profesional tienes?",
    help: "Cuenta la experiencia laboral después de tu primer título.",
    options: [
      { value: "sin_experiencia", label: "Aún no tengo experiencia" },
      { value: "menos_2", label: "Menos de 2 años" },
      { value: "2_5", label: "Entre 2 y 5 años" },
      { value: "6_10", label: "Entre 6 y 10 años" },
      { value: "mas_10", label: "Más de 10 años" },
    ],
  },
  {
    id: "prioritySkill",
    type: "choice",
    shortLabel: "Competencia prioritaria",
    text: "¿Qué competencia deseas fortalecer con mayor prioridad?",
    help: "Elige la que más necesitas para llegar al cargo al que aspiras.",
    options: [
      { value: "liderazgo", label: "Liderazgo de equipos" },
      { value: "estrategia", label: "Pensamiento estratégico" },
      { value: "analisis_datos", label: "Análisis de datos" },
      { value: "ia", label: "Inteligencia artificial aplicada" },
      { value: "programacion", label: "Programación" },
      { value: "proyectos", label: "Gestión de proyectos" },
      { value: "finanzas", label: "Finanzas y presupuestos" },
      { value: "marketing_digital", label: "Marketing digital" },
      { value: "negociacion", label: "Negociación y ventas" },
      { value: "comunicacion", label: "Comunicación efectiva" },
      { value: "gestion_cambio", label: "Innovación y emprendimiento" },
      { value: "normatividad", label: "Normatividad y cumplimiento" },
      { value: "investigacion", label: "Investigación" },
      { value: "pedagogia_digital", label: "Pedagogía y ambientes virtuales" },
      { value: "ciberseguridad", label: "Ciberseguridad" },
      { value: "ingles", label: "Inglés y otros idiomas" },
      { value: "otra", label: "Otra competencia" },
    ],
  },
  {
    id: "preferredModality",
    type: "choice",
    shortLabel: "Modalidad preferida",
    text: "¿Qué modalidad de formación prefieres?",
    help: "Piensa en cómo te resulta más fácil estudiar con tu rutina actual.",
    options: [
      { value: "virtual", label: "100 % virtual" },
      { value: "virtual_en_vivo", label: "Virtual con sesiones en vivo" },
      { value: "hibrida", label: "Híbrida" },
      { value: "presencial", label: "Presencial" },
      { value: "indiferente", label: "Me resulta indiferente" },
    ],
  },
  {
    id: "mainEducationBarrier",
    type: "choice",
    shortLabel: "Principal barrera",
    text: "¿Cuál es tu principal barrera para seguir formándote?",
    help: "Saberlo nos ayuda a diseñar opciones que se ajusten a tu realidad.",
    options: [
      { value: "costo", label: "Costo de la formación" },
      { value: "tiempo", label: "Falta de tiempo" },
      { value: "horarios", label: "Horarios poco flexibles" },
      { value: "programa_adecuado", label: "No encuentro el programa adecuado" },
      { value: "familiares", label: "Responsabilidades familiares" },
      { value: "ninguna", label: "No tengo barreras actualmente" },
    ],
  },
  {
    id: "preferredGraduateService",
    type: "choice",
    shortLabel: "Servicio más valioso",
    text: "¿Qué servicio de UNIR sería más valioso para tu desarrollo?",
    help: "Elige el que más usarías en los próximos meses.",
    options: [
      { value: "bolsa_empleo", label: "Bolsa de empleo y vacantes" },
      { value: "orientacion", label: "Orientación profesional" },
      { value: "networking", label: "Networking con otros egresados" },
      { value: "descuentos", label: "Descuentos en formación" },
      { value: "mentorias", label: "Mentorías con expertos" },
      { value: "eventos", label: "Eventos y actualización profesional" },
    ],
  },
];

export const TOTAL_QUESTIONS = SURVEY_QUESTIONS.length;
